# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Tippecanoe
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libsqlite3-dev zlib1g-dev
        git clone https://github.com/felt/tippecanoe.git
        cd tippecanoe
        make -j
        sudo make install
    - name: Install GDAL (for ogr2ogr)
      run: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin
    - run: npm ci
    - run: npm test
